<?php

defined('DEFAULT_REPOSITORY_URL') or define('DEFAULT_REPOSITORY_URL', 'https://github.com/zerotool/chosen.git');
defined('DEFAULT_REPOSITORY_COMMITS_LIMIT') or define('DEFAULT_REPOSITORY_COMMITS_LIMIT', 10);
defined('DEFAULT_REPOSITORY_COMMITS_OFFSET') or define('DEFAULT_REPOSITORY_COMMITS_OFFSET', 0);
defined('DEFAULT_GIT_COMMITS_LIST_TIME_LIMIT') or define('DEFAULT_GIT_COMMITS_LIST_TIME_LIMIT', 30);

defined('MAX_REPOSITORY_COMMITS_LIMIT') or define('MAX_REPOSITORY_COMMITS_LIMIT', 100);

return [
    'params' => [],
];
